### ISSUE TITLE
Add UI feature

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodePackage-nethermind#113]
**Is your feature request related to a problem? Please describe.**

Nethermind client has developed an UI, this is activated by enabling a flag, maybe we sure enabling these flag by default, even it could be defined in the env vars, so people can enable or disable it in a easy way.

**Describe the solution you'd like**

According to the logs by adding this options `--HealthChecks.Enabled true --HealthChecks.UIEnabled true` you should have access to the UI, itis simple but its better than nothing and for the users. Its better to have access to things like this than only the logs for normal users.

**Comment by alexpeterson91** [comment]
closed by #114
