### ISSUE TITLE
API address seems wrong

### ISSUE THREAD

**Issue by MeganerdNL** [dappnode/DAppNodePackage-nethermind#91]
At the info page of the Nethemind app there is a Api link that says: **http://nethermind.dappnode:8545**
Nothing happens when I go there when connected to VPN - page does not exist. However something **is** happenning when going to **http://nethermind.public.dappnode:8545/**. 

It seems  to me a bug with the wrong address - or am I in the wrong?

This is on Debian 11
Nethermind 1.0.21 (1.13.4 upstream)

**Comment by mgarciate** [comment]
You're right @MeganerdNL it's probably broken from this commit: https://github.com/dappnode/DAppNodePackage-nethermind/commit/8f3d7ea354361771064b207a86590435ed7a5735

cc @eduadiez
