### ISSUE TITLE
Default sync mode set to fast sync. Snap sync is much faster should be new default.

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNodePackage-nethermind#94]
**Is your feature request related to a problem? Please describe.**
Nethermind takes a long time to sync in Fast sync mode which is the default setting right now despite snapshot sync being released a long time now and it's much faster. 

**Describe the solution you'd like**
Change default sync mode to snap

**Comment by eduadiez** [comment]
Sounds good! @tropicar can you make this?

**Comment by alexpeterson91** [comment]
ok i found some other notes on this, apparently need to resync to do snap sync, can't change it once synced already. [Nethermind Docs](https://docs.nethermind.io/nethermind/ethereum-client/sync-modes#snap-sync) I've been adding a flag for sync mode snap sync on both my nethermind clients for months now, so this should be good for new installs but may be an issue for existing? anyway i can do the PR and then we can test it
